// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ufo.Database.Contexts;

#nullable disable

namespace Ufo.Database.Migrations
{
    [DbContext(typeof(UfoDbContext))]
    [Migration("20251205200359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("FsFileEntityFsFolderEntity", b =>
                {
                    b.Property<string>("FilesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentFoldersId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilesId", "ParentFoldersId");

                    b.HasIndex("ParentFoldersId");

                    b.ToTable("FsFileEntityFsFolderEntity");
                });

            modelBuilder.Entity("FsFolderEntityFsFolderEntity", b =>
                {
                    b.Property<string>("ChildFoldersId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentFoldersId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildFoldersId", "ParentFoldersId");

                    b.HasIndex("ParentFoldersId");

                    b.ToTable("FsFolderEntityFsFolderEntity");
                });

            modelBuilder.Entity("PcEntityStorageDriveEntity", b =>
                {
                    b.Property<string>("PcsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDrivesId")
                        .HasColumnType("TEXT");

                    b.HasKey("PcsId", "StorageDrivesId");

                    b.HasIndex("StorageDrivesId");

                    b.ToTable("PcEntityStorageDriveEntity");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FilesToFoldersEntity", b =>
                {
                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId", "FileId", "SnapshotId");

                    b.HasIndex("FileId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("FilesToFolders", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FoldersToFoldersEntity", b =>
                {
                    b.Property<string>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildFolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParentFolderId", "ChildFolderId", "SnapshotId");

                    b.HasIndex("ChildFolderId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("FoldersToFolders", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FsFileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FsFolderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasParent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Folders", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.PcEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pcs", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.PcsToStorageDrivesEntity", b =>
                {
                    b.Property<string>("PcId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.HasKey("PcId", "StorageDriveId", "SnapshotId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("StorageDriveId");

                    b.ToTable("PcsToStorageDrives", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.SnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FsFileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PcEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootFolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriveEntityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FsFileEntityId");

                    b.HasIndex("PcEntityId");

                    b.HasIndex("RootFolderId");

                    b.HasIndex("StorageDriveEntityId");

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.StorageDriveEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InterfaceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StorageDrives", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.VolumeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveLetter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageDriveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("VolumeSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StorageDriveId");

                    b.ToTable("Volumes", (string)null);
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.VolumeInfoEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FreeSpace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .IsUnique();

                    b.HasIndex("VolumeId");

                    b.ToTable("VolumeInfos", (string)null);
                });

            modelBuilder.Entity("FsFileEntityFsFolderEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFileEntity", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentFoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FsFolderEntityFsFolderEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", null)
                        .WithMany()
                        .HasForeignKey("ChildFoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentFoldersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcEntityStorageDriveEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.PcEntity", null)
                        .WithMany()
                        .HasForeignKey("PcsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.StorageDriveEntity", null)
                        .WithMany()
                        .HasForeignKey("StorageDrivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FilesToFoldersEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFileEntity", "File")
                        .WithMany("ParentFolderLinks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", "Folder")
                        .WithMany("FilesLinks")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.SnapshotEntity", "Snapshot")
                        .WithMany("FilesToFolders")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Folder");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FoldersToFoldersEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", "ChildFolder")
                        .WithMany("ParentFolderLinks")
                        .HasForeignKey("ChildFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", "ParentFolder")
                        .WithMany("ChildFolderLinks")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.SnapshotEntity", "Snapshot")
                        .WithMany("FoldersToFolders")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFolder");

                    b.Navigation("ParentFolder");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.PcsToStorageDrivesEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.PcEntity", "Pc")
                        .WithMany("StorageDrivesLinks")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.SnapshotEntity", "Snapshot")
                        .WithMany("PcsToStorageDrives")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.StorageDriveEntity", "StorageDrive")
                        .WithMany("PcsLinks")
                        .HasForeignKey("StorageDriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pc");

                    b.Navigation("Snapshot");

                    b.Navigation("StorageDrive");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.SnapshotEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFileEntity", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("FsFileEntityId");

                    b.HasOne("Ufo.Abstractions.Database.Entities.PcEntity", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("PcEntityId");

                    b.HasOne("Ufo.Abstractions.Database.Entities.FsFolderEntity", "RootFolder")
                        .WithMany("Snapshots")
                        .HasForeignKey("RootFolderId");

                    b.HasOne("Ufo.Abstractions.Database.Entities.StorageDriveEntity", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("StorageDriveEntityId");

                    b.Navigation("RootFolder");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.VolumeEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.StorageDriveEntity", "StorageDrive")
                        .WithMany("Volumes")
                        .HasForeignKey("StorageDriveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageDrive");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.VolumeInfoEntity", b =>
                {
                    b.HasOne("Ufo.Abstractions.Database.Entities.SnapshotEntity", "Snapshot")
                        .WithOne("VolumeInfo")
                        .HasForeignKey("Ufo.Abstractions.Database.Entities.VolumeInfoEntity", "SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ufo.Abstractions.Database.Entities.VolumeEntity", "Volume")
                        .WithMany("VolumeInfos")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Snapshot");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FsFileEntity", b =>
                {
                    b.Navigation("ParentFolderLinks");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.FsFolderEntity", b =>
                {
                    b.Navigation("ChildFolderLinks");

                    b.Navigation("FilesLinks");

                    b.Navigation("ParentFolderLinks");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.PcEntity", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("StorageDrivesLinks");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.SnapshotEntity", b =>
                {
                    b.Navigation("FilesToFolders");

                    b.Navigation("FoldersToFolders");

                    b.Navigation("PcsToStorageDrives");

                    b.Navigation("VolumeInfo");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.StorageDriveEntity", b =>
                {
                    b.Navigation("PcsLinks");

                    b.Navigation("Snapshots");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Ufo.Abstractions.Database.Entities.VolumeEntity", b =>
                {
                    b.Navigation("VolumeInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
