using System.Diagnostics.CodeAnalysis;

namespace Ufo.Abstractions;

/// <summary>
/// Where the TLS certificate the server is presenting came from. Kept as strings
/// for the same reason as <see cref="UiThemes"/>: the value travels unchanged
/// through SQLite (TEXT), JSON and the Angular client.
/// </summary>
public static class CertificateSources
{
    /// <summary>Generated by the server itself because nothing was supplied.</summary>
    public const string SelfSigned = "self-signed";

    /// <summary>Uploaded by an administrator on the Settings page.</summary>
    public const string UserSupplied = "user-supplied";

    public static readonly IReadOnlyCollection<string> All = [SelfSigned, UserSupplied];

    public static bool IsSupported([NotNullWhen(true)] string? source) =>
        source is not null && All.Contains(source, StringComparer.Ordinal);
}
